version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: appapiv1
    container_name: appapiv1
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apiV1
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
